// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepseek-completions.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const DEEPSEEK_COMPLETIONS_MODELS: ChatModelCatalog<typeof values, "deepseek-completions"> =
	flattenChatModelCatalog("deepseek-completions", values);

export const DEEPSEEK_COMPLETIONS_IMAGE_MODELS: ImageModelCatalog<typeof values, "deepseek-completions"> =
	flattenImageModelCatalog("deepseek-completions", values);

export const DEEPSEEK_COMPLETIONS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "deepseek-completions"> =
	flattenClassifierModelCatalog("deepseek-completions", values);
